# Generated by Django 6.0.3 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('lump_sum', 'Lump sum')], default='monthly', help_text='§3.2 Payment Schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='§3.2 Security Deposit', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='payment_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('lump_sum', 'Lump sum')], default='monthly', help_text='§3.2 Payment Schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='§3.2 Security Deposit', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Expected due date for this installment (§3.2 late payments).', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Expected due date for this installment (§3.2 late payments).', null=True),
        ),
    ]
