# Generated by Django 6.0.3 on 2026-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_payment_schedule_contract_security_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='security_deposit_paid',
            field=models.BooleanField(default=False, help_text='Whether the security deposit amount has been collected.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='security_deposit_received_on',
            field=models.DateField(blank=True, help_text='Date deposit was received (optional).', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='security_deposit_paid',
            field=models.BooleanField(default=False, help_text='Whether the security deposit amount has been collected.'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='security_deposit_received_on',
            field=models.DateField(blank=True, help_text='Date deposit was received (optional).', null=True),
        ),
    ]
