# Generated by Django 6.0.3 on 2026-03-28 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_tenants_to_tenant_records(apps, schema_editor):
    Contract = apps.get_model('contracts', 'Contract')
    HistoricalContract = apps.get_model('contracts', 'HistoricalContract')
    Tenant = apps.get_model('contracts', 'Tenant')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user_to_tenant = {}

    def tenant_pk_for_user(uid):
        if uid is None:
            return None
        if uid in user_to_tenant:
            return user_to_tenant[uid]
        u = User.objects.get(pk=uid)
        first = (u.first_name or '').strip()
        last = (u.last_name or '').strip()
        full = f'{first} {last}'.strip() or (u.username or str(uid))
        t = Tenant.objects.create(
            full_name=full,
            national_id=u.national_id or '',
            phone=u.phone or '',
            email=u.email or '',
            nationality='',
            date_of_birth=None,
        )
        ref = f'T-{t.pk:06d}'
        Tenant.objects.filter(pk=t.pk).update(tenant_reference=ref)
        user_to_tenant[uid] = t.pk
        return t.pk

    for uid in (
        Contract.objects.exclude(tenant_id__isnull=True)
        .values_list('tenant_id', flat=True)
        .distinct()
    ):
        tenant_pk_for_user(uid)

    for uid in (
        HistoricalContract.objects.exclude(tenant_id__isnull=True)
        .values_list('tenant_id', flat=True)
        .distinct()
    ):
        if uid not in user_to_tenant:
            tenant_pk_for_user(uid)

    for c in Contract.objects.iterator():
        if c.tenant_id:
            c.tenant_new_id = user_to_tenant[c.tenant_id]
            c.save(update_fields=['tenant_new_id'])

    for h in HistoricalContract.objects.iterator():
        if h.tenant_id:
            h.tenant_new_id = user_to_tenant[h.tenant_id]
            h.save(update_fields=['tenant_new_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_security_deposit_paid_and_admin_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_reference', models.CharField(blank=True, editable=False, help_text='Display ID e.g. T-000042', max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(db_index=True, help_text='National ID or Iqama number', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contracts.tenant'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='tenant_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.tenant'),
        ),
        migrations.RunPython(migrate_user_tenants_to_tenant_records, noop_reverse),
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='tenant',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='tenant_new',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='historicalcontract',
            old_name='tenant_new',
            new_name='tenant',
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.tenant'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.tenant'),
        ),
    ]
