# Generated by Django 6.0.3 on 2026-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('owner', 'Owner')], default='accountant', max_length=20),
        ),
    ]
