# Generated by Django 6.0.3 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tenant / user national ID or Iqama (§3.2 Tenant ID).', max_length=50),
        ),
    ]
