# Generated by Django 6.0 — office-only deployment: no external Owner login role.

from django.db import migrations, models


def reassign_owner_login_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='owner').update(role='accountant')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_national_id'),
    ]

    operations = [
        migrations.RunPython(reassign_owner_login_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('property_manager', 'Property Manager'),
                    ('accountant', 'Accountant'),
                    ('finance_manager', 'Finance Manager'),
                ],
                default='accountant',
                max_length=20,
            ),
        ),
    ]
