# Generated by Django 6.0.3 on 2026-03-23 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_units', models.IntegerField(default=1)),
                ('ownership_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('office', 'Office'), ('shop', 'Shop'), ('villa', 'Villa')], max_length=20)),
                ('rental_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='vacant', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
    ]
