# Generated by Django 6.0.3 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_historicalproperty_historicalpropertyunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='location',
            field=models.CharField(blank=True, help_text='Street / landmark / additional location detail (§3.1 Location).', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, help_text='Business Property ID (requirement §3.1).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Street / landmark / additional location detail (§3.1 Location).', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, help_text='Business Property ID (requirement §3.1).', max_length=50, null=True, unique=True),
        ),
    ]
