# Generated by Django 6.0.3 on 2026-03-28 15:05

from django.db import migrations, models


def backfill_owner_reference(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for p in Property.objects.filter(owner_reference__isnull=True).iterator():
        Property.objects.filter(pk=p.pk).update(
            owner_reference=f'O-{p.pk:06d}',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_historicalproperty_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_bank_iban',
            field=models.CharField(blank=True, help_text='Bank account / IBAN for rent payouts.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='owner_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated id e.g. O-000042 after save.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_bank_iban',
            field=models.CharField(blank=True, help_text='Bank account / IBAN for rent payouts.', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated id e.g. O-000042 after save.', max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_owner_reference, migrations.RunPython.noop),
    ]
