# Generated by Django 6.0.3 on 2026-03-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('personal', 'Personal'), ('third_party', 'Third Party')], max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=50)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('management_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_share_model', models.TextField(blank=True)),
                ('management_agreement', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property')),
            ],
        ),
    ]
